### PR TITLE
PowerMax: Volume Replication Type Upgrade/Downgrade

### PR DESCRIPTION
**Pull request by IliaRN**
# Description
This PR addresses an issue with PowerMax: Volume Replication Type Upgrade/Downgrade. 

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/265 |
|https://github.com/dell/csm/issues/266 |

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [ ] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [x] Did you run tests in a real Kubernetes cluster?
- [x] Backward compatibility is not broken

### CODE REVIEW

**Comment by shanmydell** [comment]
@IliaRN : Please raise the corresponding documentation PR , add it to release notes of PMAX

**Comment by walker2** [comment]
Doc PR: https://github.com/dell/csm-docs/pull/221

**Review by walker2 — APPROVED** [review]
looks good

**Review by boyamurthy — APPROVED** [review]
LGTM.

**Pull request merged**
