### PR TITLE
Updates request objects for replication int test

### PR DESCRIPTION
**Pull request by delldubey**
# Description
This PR fixes failing integration tests. Updating the request object as per newly introduced replication params fixes the issue.
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/138|
|https://github.com/dell/csm/issues/143|

# Checklist:

- [x] Have you run format, vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [x] Did you run tests in a real Kubernetes cluster?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
Unit test. integration and Cluster tests.

### CODE REVIEW

**Comment by shanmydell** [comment]
@delldubey : Add the Remote SRP changes in this file as well https://github.com/dell/csi-powermax/blob/main/env.sh

**Review by shanmydell — CHANGES_REQUESTED** [review]
Remote SRP id has to be added in env.sh as well

**Comment by delldubey** [comment]
> Remote SRP id has to be added in env.sh as well

Added

**Review by shanmydell — APPROVED** [review]

**Review by rajendraindukuri — APPROVED** [review]

**Review by mahesr2 — APPROVED** [review]
Changes looks good

**Pull request merged**
