### PR TITLE
Fixed Defect in service.go

### PR DESCRIPTION
**Pull request by daniyaliqbal2024**
# Description
Introducing a error check for setting array related data to envs in csi-powermax

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1499 |

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [ ] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Ran sucessful gosec./... test and make unit-test with screenshots below

### CODE REVIEW

**Comment by daniyaliqbal2024** [comment]
image

**Review by abhi16394 — APPROVED** [review]
LGTM

**Review by gallacher — CHANGES_REQUESTED** [review]
Please add unit tests to test these new lines of code.  Also, the summary line indicates you're fixing a defect but I don't think there is a defect for this? This is addressing technical debt is it not?

**Comment by anandrajak1** [comment]
@daniyaliqbal2024 - GitHub mapping was wrong. Can you create the defect in github and map it.

**Comment by daniyaliqbal2024** [comment]
unit-test-result

**Review by donatwork — APPROVED** [review]
I viewed the code coverage and it is an adequate fix for the problem. The cost of testing that the error is actually logged is something that we could do but it is costly to change in the current code.

**Review by gallacher — APPROVED** [review]

**Pull request merged**
