### PR TITLE
go version bump-up

### PR DESCRIPTION
**Pull request by nitesh3108**
Updating go version to latest available i.e. => 1.22

### CODE REVIEW

**Review by boyamurthy — COMMENTED** [review]
hi @nitesh3108  , please update go version here as well.
https://github.com/dell/csi-powermax/blob/go-version-bumpup-1.22/csireverseproxy/go.mod#L3

after updating go version, please run "make clean build" so that it will update if there any package updates.

**Comment by nitesh3108** [comment]
> hi @nitesh3108 , please update go version here as well. https://github.com/dell/csi-powermax/blob/go-version-bumpup-1.22/csireverseproxy/go.mod#L3
> 
> after updating go version, please run "make clean build" so that it will update if there any package updates.

Sure.
its running "go mod tidy" post version update

**Review by AronAtDell — APPROVED** [review]

**Review by hoppea2 — APPROVED** [review]

**Review by chimanjain — APPROVED** [review]
LGTM

**Review by delldubey — APPROVED** [review]
lgtm

**Pull request merged**
