### PR TITLE
Set StandAlone proxy mode as default and remove configmap option

### PR DESCRIPTION
**Pull request by AkshaySainiDell**
# Description
Previously, the reverseproxy supported two modes:
1. Linked
2. StandAlone

The Linked mode was deprecated in CSM 1.9.0 due to lack of usage by customers, leaving only the StandAlone mode.   https://github.com/dell/csm/issues/991

This PR sets the StandAlone proxy mode as the default and eliminates the ability to change it via configmap.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#1567|

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [x] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [x] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
- [x] Deployed driver using Helm: Successfully ran sanity tests to ensure proper functionality.
- [x] Deployed driver with CSM-Operator: Successfully ran sanity tests to confirm the deployment and operation were as expected.
- [x] Executed operator e2e with Authorization V2
cert-csi results
[cert-csi-logs.txt.txt](https://github.com/user-attachments/files/17929424/cert-csi-logs.txt.txt)

```
[root@master-1-vxa4Qh4cj2ZFH ~]# ./cert-csi certify --cert-config /root/certify.yaml --vsc powermax-iscsi > /root/cert-out1.txt
[2024-11-18 10:20:26]  INFO Starting cert-csi; ver. 1.4.0
[2024-11-18 10:20:26] FATAL can't find config file: While parsing config: yaml: invalid leading UTF-8 octet
[root@master-1-vxa4Qh4cj2ZFH ~]# ./cert-csi certify --cert-config /root/certify.yaml --vsc powermax-iscsi > /root/cert-out1.txt
[2024-11-18 10:21:16]  INFO Starting cert-csi; ver. 1.4.0
[2024-11-18 10:21:16]  INFO Suites to run with powermax-iscsi storage class:
[2024-11-18 10:21:16]  INFO 1. VolumeIoSuite {volumes: 2, volumeSize: 1075445760 chains: 2-2}
[2024-11-18 10:21:16]  INFO 2. ScalingSuite {replicas: 2, volumes: 5, volumeSize: 1075445760}
[2024-11-18 10:21:16]  INFO 3. CloneVolumeSuite {pods: 2, volumes: 1, volumeSize: 1075445760}
[2024-11-18 10:21:16]  INFO 4. VolumeExpansionSuite {pods: 1, volumes: 1, size: 1075445760, expSize: 2150891520, block: false}
[2024-11-18 10:21:16]  INFO 5. SnapSuite {snapshots: 3, volumeSize; 1075445760}
[2024-11-18 10:21:16]  INFO 6. ReplicationSuite {pods: 2, volumes: 5, volumeSize: 1075445760}

[2024-11-18 10:21:41]  INFO Using EVENT observer type
[2024-11-18 10:21:41]  INFO Using default config
[2024-11-18 10:21:41]  INFO Successfully loaded config. Host: https://10.247.22.239:6443
[2024-11-18 10:21:41]  INFO Created new KubeClient
[2024-11-18 10:21:41]  INFO Running 1 iteration(s)
[2024-11-18 10:21:41]  INFO     *** ITERATION NUMBER 1 ***
[2024-11-18 10:21:41]  INFO Starting ReplicationSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Successfully created namespace replication-suite-dde1cc2b
[2024-11-18 10:21:41]  INFO Starting ScalingSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Starting SnapSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Successfully created namespace scale-test-cf27be8c
[2024-11-18 10:21:41]  INFO Using default image: docker.io/centos:latest
[2024-11-18 10:21:41]  INFO Starting CloneVolumeSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Successfully created namespace snap-test-0c506249
[2024-11-18 10:21:41]  INFO Starting VolumeExpansionSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Starting VolumeIoSuite with powermax-iscsi storage class
[2024-11-18 10:21:41]  INFO Created stateful set sts-scale-testrq8zj
[2024-11-18 10:21:41]  INFO Using default image: docker.io/centos:latest
................
[2024-11-18 10:23:34]  INFO Executing command: [/bin/bash -c sha512sum /data0/writer-0.data > /data0/writer-0.sha512]
[2024-11-18 10:23:40]  INFO Waiting until no Volume Attachments with PV  left
[2024-11-18 10:23:40]  INFO VolumeAttachment deleted
[2024-11-18 10:23:40]  INFO Deleting all resources in namespace volumeio-test-6ed9d9e9
[2024-11-18 10:23:42]  INFO All pods are ready in 1m6.001579863s
[2024-11-18 10:23:42]  INFO Deleting all resources in namespace clonevolume-suite-87efc403
[2024-11-18 10:23:42]  INFO Creating new pods with replicated volumes mounted on them
[2024-11-18 10:23:43]  INFO Waiting for all pods in replication-suite-dde1cc2b to be READY
[2024-11-18 10:23:46]  INFO pod-prov-test-cjtbk/data0 was successfully expanded
[2024-11-18 10:23:46]  INFO Deleting all resources in namespace volume-expansion-suite-7c5c54a1
[2024-11-18 10:23:48]  INFO SUCCESS: ScalingSuite in 2m7.413254912s
[2024-11-18 10:23:52]  INFO Namespace volumeio-test-6ed9d9e9 was deleted in 12.016835779s
[2024-11-18 10:23:52]  INFO Waiting for volumeattachments to be deleted
[2024-11-18 10:23:54]  INFO Namespace clonevolume-suite-87efc403 was deleted in 12.018848937s
[2024-11-18 10:23:54]  INFO Waiting for volumeattachments to be deleted
[2024-11-18 10:23:58]  INFO Namespace volume-expansion-suite-7c5c54a1 was deleted in 12.262574615s
[2024-11-18 10:23:58]  INFO Waiting for volumeattachments to be deleted
[2024-11-18 10:24:00]  INFO Waiting for Snapshot 'snap1' to be READY
[2024-11-18 10:24:11]  INFO SUCCESS: VolumeIoSuite in 2m30.275042319s
[2024-11-18 10:24:15]  INFO SUCCESS: VolumeExpansionSuite in 2m34.890461767s
[2024-11-18 10:24:16]  INFO SUCCESS: CloneVolumeSuite in 2m34.941062837s
[2024-11-18 10:24:42]  INFO Waiting for Snapshot 'snap2' to be READY
[2024-11-18 10:24:49]  INFO All pods are ready in 1m6.40137845s
[2024-11-18 10:24:49]  INFO The replication group name from pvc is
[2024-11-18 10:24:49]  INFO Deleting all resources in namespace replication-suite-dde1cc2b
[2024-11-18 10:25:14]  INFO Restoring from snap1
[2024-11-18 10:25:14]  INFO Creating pvc snap1-restore
[2024-11-18 10:25:14]  INFO Waiting for pod snap1-restore-pod to be READY
[2024-11-18 10:25:19]  INFO Namespace replication-suite-dde1cc2b was deleted in 30.018310443s
[2024-11-18 10:25:19]  INFO Deletion callback function is not empty, calling it
[2024-11-18 10:25:19]  INFO Deleting local RG
[2024-11-18 10:25:19]  WARN error when deleting local RG: no matches for kind "DellCSIReplicationGroup" in version "replication.storage.dell.com/v1"
[2024-11-18 10:25:19]  INFO Sleeping for 1 minute...
[2024-11-18 10:25:52]  INFO Checker pod: snap1-restore-pod
[2024-11-18 10:25:52]  INFO Executing command: [/bin/bash -c sha512sum -c /data0/writer-0.sha512]
[2024-11-18 10:26:21]  INFO Hashes match
[2024-11-18 10:26:21]  INFO Deleting all resources in namespace snap-test-0c506249
[2024-11-18 10:26:24]  INFO SUCCESS: ReplicationSuite in 4m43.234465341s
[2024-11-18 10:26:47]  INFO Namespace snap-test-0c506249 was deleted in 26.011475513s
[2024-11-18 10:26:51]  INFO SUCCESS: SnapSuite in 5m10.296877158s
[2024-11-18 10:26:51]  INFO Started generating reports...
6 / 6 [--------------------------------------------------------------------------------------------] 100.00% ? p/s
[2024-11-18 10:26:51]  INFO Started generating reports...
6 / 6 [--------------------------------------------------------------------------------------------] 100.00% ? p/s
6 / 6 [--------------------------------------------------------------------------------------------] 100.00% 7 p/s
[2024-11-18 10:26:52]  WARN No ResourceUsageMetrics provided
[2024-11-18 10:26:52] ERROR no ResourceUsageMetrics provided
[2024-11-18 10:26:52]  INFO Avg time of a run:   153.93s
[2024-11-18 10:26:52]  INFO Avg time of a del:   27.39s
[2024-11-18 10:26:52]  INFO Avg time of all:     196.84s
[2024-11-18 10:26:52]  INFO During this run 100.0% of suites succeeded

```
image (24)

### CODE REVIEW

**Review by hoppea2 — COMMENTED** [review]
Please add more detailed description of the fix and automation test results once available

**Review by jooseppi-luna — CHANGES_REQUESTED** [review]
There is no description in the PR, and there is no explanation of how this was tested. Please update the PR with both.

**Review by shanmydell — DISMISSED** [review]

**Review by abhi16394 — APPROVED** [review]

**Review by adarsh-dell — DISMISSED** [review]
Change the Copyright year for some of the file that is not updated, rest looks good to me.

**Review by shanmydell — APPROVED** [review]

**Review by adarsh-dell — APPROVED** [review]

**Comment by alikdell** [comment]
Is this impact Authorization? I guess so, I didn't hear much about tis work. Please make sure Authorization V2 works with this changes.

**Review by jooseppi-luna — CHANGES_REQUESTED** [review]
Thanks for updating PR description -- can you test with auth as well, since reverseproxy has to talk directly to auth?

**Comment by AkshaySainiDell** [comment]
@alikdell @jooseppi-luna, The team has successfully tested the changes with authorization. The results are now included in the PR description.

**Review by alikdell — APPROVED** [review]

**Pull request merged**
