### PR TITLE
Testing action

### PR DESCRIPTION
**Pull request by medegw01**
Updating unit tests to Github actions

### CODE REVIEW

**Comment by prablr79** [comment]
@medegw01 any reason this PR is getting updated ?

**Comment by medegw01** [comment]
> @medegw01 any reason this PR is getting updated?
I've replied to you via slack. Please view my message on  `#csi-general` channel

**Comment by hoppea2** [comment]
This will be addressed out of release schedule

**Comment by prablr79** [comment]
@medegw01 if this is not a valid PR can we close this PR ?

**Comment by shanmydell** [comment]
> @medegw01 if this is not a valid PR can we close this PR ?

Hi @prablr79 : It is a valid PR and a valid action , but PowerMax unit tests are failing with Data Race Error, Once it is fixed this PR will be merged

**Comment by prablr79** [comment]
@shanmydell  thanks, if we are not planning address in current sprint, lets move this PR out.

**Pull request closed without merging**
