### PR TITLE
Fixes for line feed interpreted as String

### PR DESCRIPTION
**Pull request by shanmydell**
# Description

Logrus will have a new line at starting of each log,  line feed has not been interpreted. PR fixes the same.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|  https://github.com/dell/csm/issues/251 |

# Checklist:

- [X] Have you run format,vet & lint checks against your submission?
- [X] Have you made sure that the code compiles?
- [X] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

### CODE REVIEW

**Review by boyamurthy — APPROVED** [review]
looks good to me.

**Review by delldubey — APPROVED** [review]
lgtm

**Review by delldubey — APPROVED** [review]
LGTM, please validate before merging

**Comment by shanmydell** [comment]
There is an issue with WINDOWS vs Linux ASCII characters, will open new PR

**Pull request closed without merging**
