### PR TITLE
Updating the Golang version to 1.17

### PR DESCRIPTION
**Pull request by boyamurthy**
Updating Golang version to 1.17 to have latest security fixes .

| GitHub Issue # |
| -------------- |
|   https://github.com/dell/csm/issues/149                    |

# Checklist:

- [X] Have you run format,vet & lint checks against your submission?
- [X] Have you made sure that the code compiles?
- [X] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [X] Did you run tests in a real Kubernetes cluster?
- [ ] Backward compatibility is not broken

### CODE REVIEW

**Comment by shanmydell** [comment]
@boyamurthy go: golang.org/x/net@v0.0.0-20211015210444-4f30a5c0130f requires
	golang.org/x/sys@v0.0.0-20210423082822-04245dca01da: missing go.sum entry; to add it:
	go mod download golang.org/x/sys - > Checks are failing

**Comment by boyamurthy** [comment]
> @boyamurthy go: golang.org/x/net@v0.0.0-20211015210444-4f30a5c0130f requires golang.org/x/sys@v0.0.0-20210423082822-04245dca01da: missing go.sum entry; to add it: go mod download golang.org/x/sys - > Checks are failing

Fixed the error @shanmydell .

**Review by delldubey — APPROVED** [review]
lgtm

**Review by shanmydell — APPROVED** [review]
LGTM

**Pull request merged**
